name: pipeline

on: [push, pull_request]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: testenv
        python-version: ${{ matrix.python-version }}
    - shell: bash -l {0}
    - name: Install dependencies
      run: |
        conda install -c conda-forge --file requirements.txt
        conda install pytest pytest-cov
    - name: Test with pytest
      run: |
        pytest --cov=./covid --cov-report term-missing covid/tests.py
    - name: Run dedicated coverage step
      if: matrix.python-version == 3.7
      run: |
        pytest --cov=./covid --cov-report xml --cov-report term-missing covid/tests.py
